import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import Footer from "@/components/shared/Footer";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nebs-it Notice Board",
  description: "Generated by Nebs Tech",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} antialiased`}
      >
        <div className="md:grid grid-cols-5">
          <aside className="col-span-1 bg-white">
            <Sidebar />
          </aside>
          <div className="col-span-4">
            <ReactQueryProvider>
              <Navbar />
              <main className="p-4 min-h-screen">{children}</main>
            </ReactQueryProvider>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
